name: Release Android

# only when version file changes, the action runs
# tag triggering doesn't support caching
on:
  push:
    paths:
      - "android/**"
      - ".github/workflows/release-android.yml"

env:
  SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
  KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
  RELEASE_KEY_STORE_BASE64: ${{ secrets.ANDROID_KEYSTORE }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create service-account.json
        run: echo -n "$SERVICE_ACCOUNT_JSON" > service-account.json

      - name: Insert keystore properties
        run: |
          sed -i -e "s%STORE_PASSWORD%${{env.STORE_PASSWORD}}%g" android/build.gradle
          sed -i -e "s%KEY_PASSWORD%${{env.KEYSTORE_PASSWORD}}%g" android/build.gradle
          sed -i -e "s%KEYSTORE_ALIAS%${{env.KEYSTORE_ALIAS}}%g" android/build.gradle

      - name: Create release keystore
        run: echo -n "$RELEASE_KEY_STORE_BASE64" | base64 --decode > android/keystore.keystore

      - name: Export signed apk and release to internal testing
        uses: dulvui/libgdx-android-release@v1.0
        with:
          package-name: com.salvai.snake