name: Release Android

# only when version file changes, the action runs
# tag triggering doesn't support caching
on:
  push:
    paths:
      - "android/**"
      - ".github/workflows/release-android.yml"

env:
  RELEASE_KEY_STORE_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
  SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create service-account.json
        run: echo $SERVICE_ACCOUNT_JSON > service-account.json

      - name: Create keystore.properties
        run: echo $KEYSTORE_PROPERTIES > keystore.properties

      - name: Create release keystore
        run: echo $RELEASE_KEY_STORE_BASE64 | base64 --decode > keystore.keystore

      - name: Export signed apk and release to internal testing
        uses: dulvui/libgdx-android-release@v0.1
        with:
          package-name: com.salvai.snake